### ISSUE TITLE
Issue with AMD shadow pack

### ISSUE THREAD

**Issue by dadafui** [ActualMandM/cemu_graphic_packs#301]
Hello and thank's for your work.

I still see a big issue with shadows with my RX580 (same on my old 280x)
I activated AMD shadow graphic pack but I still see some weird issues on world, buildings and hedges shadows, for example here a video, look at the building and hedges shadow when moving. 
https://www.youtube.com/watch?v=JHkWEw1QWgw&lc

any way to fix this ? thank you

**Comment by ActualMandM** [comment]
hello! going through and checking old issues to close, does this issue still happen with the latest version of cemu?

**Comment by dadafui** [comment]
hello, fixed with the vulkan API :)
