### ISSUE TITLE
Floating objects do not work correctly in the Hila Rao temple with the FPS++ mod

### ISSUE THREAD

**Issue by PlagueRus** [ActualMandM/cemu_graphic_packs#331]
Floating objects do not work correctly in the Hila Rao shrine with the FPS++ mod.
The barrels and the chest do not float along the path and get stuck against the wall. 
Wooden platforms float at the wrong speed or get stuck.
![barrels](https://user-images.githubusercontent.com/6636382/52313006-e8a20200-29bd-11e9-8242-27b5d5c2893b.jpg)
![woodenplatform](https://user-images.githubusercontent.com/6636382/52313007-e8a20200-29bd-11e9-8755-481b3184d233.jpg)

**Comment by Xalphenos** [comment]
This is a known issue when running the game above 30 FPS.

**Comment by poudink** [comment]
this should be fixed by the new fps++ update
