### ISSUE TITLE
[Paper Mario: color spash] Textures aren't transparent !

### ISSUE THREAD

**Issue by kn900** [ActualMandM/cemu_graphic_packs#455]
Objects which has to be transparent like cloth , waterfalls are just solid. Without tutorial I cannot complete Indigo Underground ( waterfall cutout) and Marmalade Valley is pain to find hidden objects. 
![obraz](https://user-images.githubusercontent.com/68546927/87938411-da06b800-ca96-11ea-91f1-a6b0221a9e86.png)
![obraz](https://user-images.githubusercontent.com/68546927/87941118-ebea5a00-ca9a-11ea-8733-1f268a2115ec.png)

**Comment by Crementif** [comment]
Can you confirm that this bug happens without any graphic packs?

**Comment by kn900** [comment]
![obraz](https://user-images.githubusercontent.com/68546927/87966934-4fd24a00-cabe-11ea-9ba5-a7b97e332ce3.png)
Yes, still the same.I'm using Vulcan api, because game experience is way smother.

**Comment by slashiee** [comment]
Does this happen on OpenGL as well?

**Comment by kn900** [comment]
yes , this occur also in OpenGL



------------------
My System Information
------------------
         Operating System: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
                 Language: Polish (Regional Setting: Polish)
      System Manufacturer: Micro-Star International Co., Ltd.
             System Model: MS-7A34
                     BIOS: A.LQ (type: UEFI)
                Processor: AMD Ryzen 5 1500X Quad-Core Processor           (8 CPUs), ~3.5GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8146MB RAM
                Page File: 5136MB used, 11202MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 110 DPI (114 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Enabled
                 Miracast: Available, with HDCP
                    AMD-V:Distabled 
---------------
Display Devices
---------------
           Card name: NVIDIA GeForce GTX 1070
        Manufacturer: NVIDIA
           Chip type: GeForce GTX 1070
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
    Dedicated Memory: 8088 MB
        Current Mode: 2560 x 1440 (32 bit) (120Hz)
      NVIDIA Driver Version: 451.67

**Comment by ActualMandM** [comment]
Does this still happen with the latest version of Cemu?
