### ISSUE TITLE
[Paper Mario: Color Spash] Violet Passage: Ship's sail texture glitch

### ISSUE THREAD

**Issue by kn900** [ActualMandM/cemu_graphic_packs#456]
Happens only on Vulcan, openGL works fine
![obraz](https://user-images.githubusercontent.com/68546927/88276088-c2217500-ccde-11ea-9acf-4b84ddd68b45.png)
![obraz](https://user-images.githubusercontent.com/68546927/88276679-c306d680-ccdf-11ea-8a0d-470f245762e9.png)
![obraz](https://user-images.githubusercontent.com/68546927/88276890-16792480-cce0-11ea-9c27-98022c55c95f.png)

**Comment by ActualMandM** [comment]
Closing since this is a Cemu issue. If it's still occurring with the latest version, report it to their bug tracker.
