### ISSUE TITLE
Kirby and RC: Flashing Squares workaround not needed anymore

### ISSUE THREAD

**Issue by v1993** [ActualMandM/cemu_graphic_packs#467]
Flashing squares issue does not happen on recent cemu versions.

**Comment by Crementif** [comment]
We usually don't remove packs whenever they become no longer needed since someone might want to use the latest graphic packs with older Cemu versions that don't have this fix. Is there any problem the pack causes when enabled?

**Comment by slashiee** [comment]
Considering we're now transitioning to v6 packs, I think it'd safe to remove the pack now. Leaving it up to you though
