### ISSUE TITLE
BotW Graphic Pack Weather Mod Issue

### ISSUE THREAD

**Issue by Peduls** [ActualMandM/cemu_graphic_packs#468]
When trying to change the weather via the "Weather" graphic pack mod in Breath of the Wild it displays this error message.
![Capture](https://user-images.githubusercontent.com/34750422/93551216-93b0c680-f92a-11ea-8567-d8f627f510ee.PNG)

**Comment by DaRkL3AD3R** [comment]
Confirming this as well.

**Comment by Crementif** [comment]
Let me know if this fixes the issue for y'all. The weather pack was always a bit iffy, but this seems to fix it.

**Comment by Peduls** [comment]
It's fixed as in the error no longer occurs. Before it displayed the error message but the weather still changed. Now the weather doesn't change at all...

**Comment by Peduls** [comment]
![Capture](https://user-images.githubusercontent.com/34750422/93689144-1354a780-fa89-11ea-8a6e-5a8e8af73eff.PNG)

**Comment by Peduls** [comment]
Attempting to change the weather crashed my instance of CEMU.
[log.txt](https://github.com/ActualMandM/cemu_graphic_packs/files/5733115/log.txt)

**Comment by Peduls** [comment]
It appears this has been fixed.

**Comment by Crementif** [comment]
Fixed in https://github.com/ActualMandM/cemu_graphic_packs/commit/ca22977ef03e4a826f3bfe7f0df92447437c4219
