### ISSUE TITLE
Tekken Tag Tournament 2

### ISSUE THREAD

**Issue by Andrew-Twins** [ActualMandM/cemu_graphic_packs#476]
Some stages are too bright, like too much blooming.

Nvidia 1060 6GB gpu.
Nvidia driver version 457.30 WHQL.
AMD FX8350 cpu.
CEMU version 1.22.0k (Win x64)
OpenGL (because Vulkan causes a glitch with Lili's hair and other things...)

**Comment by ActualMandM** [comment]
Closing since this is a Cemu issue. If it's still occurring with the latest version, report it to their bug tracker.
