### ISSUE TITLE
[XenobladeX] The 60pfs patch does not work properly in the JPN version

### ISSUE THREAD

**Issue by Iridescent-me** [ActualMandM/cemu_graphic_packs#479]
Sorry, my English is not very good.

Can this patch work in the Japanese version?
I opened it, but I can only have 60 FPS.
soul voices and QTE too fast...I always die in battle...It's too difficult for me.

Just fix this one...Thanks! please!

**Comment by LuckilyCrazy** [comment]
Can someone help me? Please

**Comment by lasyan3** [comment]
Problem is to get a japanese version of the game...

**Comment by LuckilyCrazy** [comment]
> Problem is to get a japanese version of the game...

Thank you for your reply!
I'm sorry for my inconsideration on this problem..
Can you find other ways to resolve it?

**Comment by ActualMandM** [comment]
Does this issue still happen with the latest graphic packs version? I know the FPS patch has recently been revamped.

**Comment by intra2** [comment]
it does not if you are using, FPS++ works on JP 1.0.2

**Comment by Crementif** [comment]
yeah, the 60FPS patch is replaced by FPS++. So this issue can be closed then?

**Comment by intra2** [comment]
it can be
