### ISSUE TITLE
[Mario Kart 8] Why 5120x1440 (32:9) resolution has been removed ?

### ISSUE THREAD

**Issue by YoPrez** [ActualMandM/cemu_graphic_packs#480]
I just updated CEMU graphic pack and realized that 5120x1440 (32:9) resolution for MK8 has been removed. (the "src/MarioKart8/Graphics/rules.txt" file has been edited in the last commit).
Can you explain why ?
I have a Samsung C49HG90 and the 5120x1440 (32:9) resolution was absolutely perfect ! MK8 was displayed on the whole screen. 5120x1440 (32:9) resolution is just perfetc for racing games on that type of monitor.
I'm very sad and disappointed.
Can you get this [Preset] back please ?

**Comment by ActualMandM** [comment]
Forgot to check for resolutions when copy-pasting the Splatoon ones, whoops

Will fix in a moment

**Comment by YoPrez** [comment]
Thank you :)
