### ISSUE TITLE
[Super Smash Bros. for Wii U] Missing non-integer resolutions with v6 Graphic pack

### ISSUE THREAD

**Issue by walikor** [ActualMandM/cemu_graphic_packs#481]
hi,
I noticed on the resource pack(version 719) that only the resolutions are present:
-960x540
-1920x1080
-3840x2160
-7680x4320
where is the resolution 2560x1440 (2k)?

**Comment by ActualMandM** [comment]
This is due to an existing SSB4 issue, #347 

This issue will be fixed once we fix that one
