### ISSUE TITLE
Relabel BOTW graphics fixes that are outdated

### ISSUE THREAD

**Issue by Yeasteroni** [ActualMandM/cemu_graphic_packs#485]
New users could accidentally check off graphics fixes that are no longer needed, for example, the Intel iGPU shadow fix pack is no longer needed after Cemu 1.20.1 and does more harm than good. Can such packs say "No longer needed after ___ update" in their description?

**Comment by Crementif** [comment]
Yup, we've got that all planned in a very big future update:
![sneakpeek of that](https://user-images.githubusercontent.com/26669564/103469512-176db200-4d66-11eb-957c-fa8d96e9b026.png)! That's basically what we're going for, not 100% sure on the final sorting.

**Comment by Crementif** [comment]
Addressed in https://github.com/ActualMandM/cemu_graphic_packs/commit/ca22977ef03e4a826f3bfe7f0df92447437c4219
