### ISSUE TITLE
[Xenoblade Chronicles X] CHEAT mods not working

### ISSUE THREAD

**Issue by DANNYD99** [ActualMandM/cemu_graphic_packs#486]
The Cheat mods for Skells and Augments aren't working. Any time I enter the shop to get them is freezes CEMU. These are the only ones that don't work.

It also says the patches for class EXP and Inner EXP failed to apply, but they seem to work anyway if that helps at all.

Also, Offline Squad Missions Crash Cemu on start up

Its 1.22.3b Cemu and 0.5.7.3 cemu hook.

**Comment by lasyan3** [comment]
Did you try with the last repository release? Xenoblade v5 graphic packs have been merged now.

**Comment by DANNYD99** [comment]
I just updated today and its all fine now. Thank you.
