### ISSUE TITLE
[Feature Request] configurable amount of extended memory for BOTW Extended Memory pack

### ISSUE THREAD

**Issue by MisterPrintf** [ActualMandM/cemu_graphic_packs#491]
I'd like to be able to configure this pack to extend the amount of memory even further (4gb). A setting for this would be appreciated.

**Comment by MisterPrintf** [comment]
Particularly of note here are the new Draw Distance settings, which unfortunately can't all be maxed out simply because there is not enough memory to permit it.

**Comment by Crementif** [comment]
We can't extend the memory further then 4GBs of RAM since that's outside of 32 bit address range.

What is the problem with having both maxed out? From my testing it worked fine, but I guess that might depend on the area you're in.

**Comment by ruvaldak** [comment]
Using maxed out draw distance in combination with a large mod like Second Wind can start to cause issues
