### ISSUE TITLE
The Legend of Zelda: Breath of the Wild/Mods/Draw Distance 

### ISSUE THREAD

**Issue by abcdisgreat** [ActualMandM/cemu_graphic_packs#492]
Objects Draw Distance 1
![screenshot_1](https://user-images.githubusercontent.com/33865977/104552557-f98b3180-5630-11eb-8163-4dcdb4162cef.png)

Objects Draw Distance 1.25
![screenshot_5](https://user-images.githubusercontent.com/33865977/104552699-2e978400-5631-11eb-9e15-8b239b16dae9.png)

**Comment by Crementif** [comment]
Should be fixed with https://github.com/ActualMandM/cemu_graphic_packs/commit/93bf050b4b6269fc2d780014dd005ad137526ae5
