### ISSUE TITLE
Inverse resolution for Gamepad in Xenoblade Chronicles X, fixes missing Gamepad text

### ISSUE THREAD

**Issue by Kuiriel** [ActualMandM/cemu_graphic_packs#494]
This bug may be related to the v5 (in progress) graphics packs, but they're presently archived and I was told to post here. 

Gamepad resolution in XCX does not correctly apply to second screen. The higher the Gamepad resolution, the blockier the gamepad screen. This has a secondary effect, resulting in the list of probes not being visible on the second screen when changing probes - that is, all text for probe names was not visible, yet still selectable if I  clicked randomly enough.

To fix this I LOWERED the resolution of the gamepad in the Graphics Packs to the lowest setting. Now they're nice and crisp and the missing text is also visible.

**Comment by Kuiriel** [comment]
If you need me to take a video of the bug because I've explained it poorly, I can do so.

This is when using the v5 gfx packs, which I downloaded from their github before they were archived.

Step 1. Increase game pad resolution.
Step 2. Restart game.
Step 3. Look at game pad in game. It is now blockier then before. 

Do the opposite, and it looks better instead.

On default game pad resolution when you choose to change the current probe in a region, the text that lists the different probes is hidden.

This is fixed on the 'lowest' game pad resolution, though I have not checked the other 'lower' game pad resolutions as well. 

Main screen resolution tested at hd and 4k, didn't seem to have any impact on bug.

**Comment by Crementif** [comment]
Your explanation made sense. That conversation in #gfx_packs was more about why the cause of the bug wasn't obvious. We've had other reports of some similar stuff happening too. So don't worry too much about it. I plan to look into updating everything soon!

**Comment by Crementif** [comment]
Let me know if this was actually fixed!
