### ISSUE TITLE
Child of Light missing icons bug

### ISSUE THREAD

**Issue by Itamai** [ActualMandM/cemu_graphic_packs#501]
Using latest cemu version(1.22.4) and latest graphic packs.
If i change the resolution some icons are not shown in the inventory as seen in the picture

![image](https://user-images.githubusercontent.com/53093696/105726479-6b655400-5f2a-11eb-9e57-6de82074f447.png)

Expected(default resolution):

![image](https://user-images.githubusercontent.com/53093696/105727077-ffcfb680-5f2a-11eb-8ebe-202ddf35e73c.png)

**Comment by Crementif** [comment]
Thanks for reporting this issue! I'll take a look at it this week somewhere.
