### ISSUE TITLE
[The Legend of Zelda BOTW] Game has decreased brightness

### ISSUE THREAD

**Issue by monstrkapsula** [ActualMandM/cemu_graphic_packs#504]
Game became dark, like decreased gamma
1. I updated Cemu, and graphic packs from 1.21 version to newest 1.22.6c.
2. I changed graphic packs, Clarity (I deleted all game and start play without any graphic mode - same problem)
3. My game got more black colors. Very dark
**Expected behavior**
I expected normal play, to see items on ground.
Screenshot:
![1111](https://user-images.githubusercontent.com/79452892/108702800-cdf64380-751a-11eb-837b-820263f067cf.jpg)

**Desktop**
 - OS: Windows 7
 - GPU: AMD Rx 580
 - Renderer Vulkan
 - Version 1.22.6C

**Additional context**
I have newest driver radeon adrenalin, Tried to back up it (no difference) I tried older versions of Cemu, that's also make no difference. When I use OpenGl - problem disappear. I guess some problem with Vulkan. But don't know what to do. Before update I haven't this problem. I even can't see mushrooms under trees because so dark shadows..

**Comment by Serfrost** [comment]
Sounds like your Vulkan cache had cached some kind of Shader modification or some other issue. Try deleting the shadercache\precompiled and shadercache\driver folders.

**Comment by ActualMandM** [comment]
Looks more like a sRGB issue, considering the HUD is also dark. Editing the gamma to 0.5 makes it look proper.
![image](https://user-images.githubusercontent.com/15317421/109541844-1d87c280-7a79-11eb-8732-4559acee413f.png)

**Comment by Serfrost** [comment]
You're right, I forgot about Clarity not affecting the UI.

**Comment by ActualMandM** [comment]
Does this issue still happen?

**Comment by monstrkapsula** [comment]
> 

yes, but I fixed it using older version of cemu. 
Btw I recently updated Gpu to gtx 1080ti. I can't continue this problem more

**Comment by ActualMandM** [comment]
I'll close the issue then, if it happens for anyone else I would recommend reporting it to the Cemu bug tracker as it might be a Cemu related bug.

**Comment by Squall-Leonhart** [comment]
This actually looks like the result of Forcing Full range on a display only capable of or set to limited range.
