### ISSUE TITLE
[Breath of the Wild] Fog mod doesn't work

### ISSUE THREAD

**Issue by bakugo** [ActualMandM/cemu_graphic_packs#505]
**Describe the issue**
The "Fog and Mist" mod has no effect. The old "Distant Fog Removal" version worked.

**To Reproduce**
1. Enable Fog mod, set all opacities to 0%
2. Start game
3. Fog looks the same as default

**Expected behavior**
Fog should disappear

**Screenshots**
What the game looks like normally & with fog mod enabled:
![CEMU Screenshot 2021 02 23 - 13 31 35 50](https://user-images.githubusercontent.com/6014513/108851022-e4b09f00-75db-11eb-8936-40c0ee19e779.png)
What it should look like with fog mod enabled (screenshot using the old distant fog removal):
![CEMU Screenshot 2021 02 23 - 13 34 10 22](https://user-images.githubusercontent.com/6014513/108851048-ea0de980-75db-11eb-812c-87937006b955.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: Nvidia
 - Renderer: issue affects both
 - Version: v1.22.6c

**Comment by Crementif** [comment]
Did you update your graphic packs recently? I recently tried to address this regression in functionality. Also, did you change the brightness? By default the old mods used 4x brightness or something. That might make it more alike.

**Comment by bakugo** [comment]
I am using the latest release (764) and brightness was set to 1x in both cases.
Did some more testing and it seems like the Distance Fog options are actually affecting mist clouds...

**Comment by nullavisus** [comment]
I am currently on the latest CEMU with the most recent graphics packs and can confirm that the current Fog mod is still broken. Changing the opacity of ground fog, tree fog, water fog, and distance fog all do absolutely nothing, the setting is simply non functional. The brightness settings do seem to work, however subtle they are. Reverting to the older fog pack works perfectly fine. I am currently using Vulkan as my API.

**Comment by skalfate** [comment]
The migration of the pack was not properly migrated last I became aware of the issue and had a look. For the time being use the v4 pack, in other words the last stable version of the pack for now. It should still work. It can be found in graphic packs release 708 or before. [https://actualmandm.github.io/cemu_graphic_packs/](url)

**Comment by skalfate** [comment]
Hi, I just wanted to post an update. I have ported over my older work to version 6. The new pack is now completed and works as expected. It was a nice learning experience to work with version 6 graphic pack specifications..

Attached is the pack alone on its own. Just extract and drag and drop into your cemu/graphicPacks folder.

[BreathOfTheWild_DistantFogRemoval_V6.zip](https://github.com/ActualMandM/cemu_graphic_packs/files/7317156/BreathOfTheWild_DistantFogRemoval_V6.zip)

**Comment by Crementif** [comment]
The pack made by SkalFate has been added to the official packs in the [latest major graphic pack update](https://www.reddit.com/r/cemu/comments/rp40r7/a_new_major_breath_of_the_wild_graphic_pack/), alongside a lot of other fixes.
