### ISSUE TITLE
[Breath of the Wild] FPS++ - High Refresh Rate Causes Excessive Bokoblin/Moblin Ragdolling

### ISSUE THREAD

**Issue by dimanaum** [ActualMandM/cemu_graphic_packs#526]
**Describe the issue**
I'm playing the game at 144hz using the FPS++ mod. I have noticed that the ragdolling of enemies increases greatly. For example, when I get a headshot on a bokoblin, they go absolutely flying, several times further than expected. I would assume this issue has to do with the speed of the engine being accelerated due to the higher FPS.

**To Reproduce**
1. Enable a higher refresh rate in FPS++ (it is extremely noticeable past 100FPS)
2. Cause a bokoblin to go flying due to a critical hit of some sort (I recommend a headshot with an arrow)
3. The bokoblin will be yeeted across the environment instead of flying backwards a few feet.

**Expected behavior**
I would expect the knockback/ragdolling to behave similarly to how it does in 30fps.

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: Nvidia
 - Renderer: Vulkan
 - Version: 1.2.170

**Comment by Crementif** [comment]
This is now fixed with the [new major graphic pack update](https://www.reddit.com/r/cemu/comments/rp40r7/a_new_major_breath_of_the_wild_graphic_pack/), thanks to the work of @Exzap!
