### ISSUE TITLE
[Feature Request] Option to duplicate frames to 60hz in 30fps games

### ISSUE THREAD

**Issue by duke912** [ActualMandM/cemu_graphic_packs#535]
It's more of a question to be honest, I noticed this feature added in some other emulators (PPSSPP and Dolphin comes to mind) and it kinda makes 30fps games run 'smooth'. When I play a 30fps game I always enable frame interpolation on TV and it seems to 'stutter' from time to time (also happens with interpolation disabled, just less noticeable), doesn't happen when frames are duplicated to 60fps.

So my question is: Is it possible to add such feature to Cemu? also if this is not the right place to ask for this feature, can someone direct me to the right place?

**Comment by ActualMandM** [comment]
You can submit Cemu feature requests on the [Cemu bug tracker](http://bugs.cemu.info/)
