### ISSUE TITLE
Mods Loot doesn't work with Xenoblade X Japanese Version (Ver 1.0.2)

### ISSUE THREAD

**Issue by gikirima** [ActualMandM/cemu_graphic_packs#539]
As written on the title.
it seems activated when I saw the log, but the result isn't doing. I'm activating all mods for loot for 100% drop force type etc., but it didn't drop the forced treasure even after like 5-10 battle. Could anyone help me?
[log.txt](https://github.com/ActualMandM/cemu_graphic_packs/files/7574564/log.txt)

**Comment by intra2** [comment]
this issue has been fixed with pull 567 and can be safely closed now
