### ISSUE TITLE
[BotW] "Static" FPS++ changes game speed

### ISSUE THREAD

**Issue by ZwipZwapZapony** [ActualMandM/cemu_graphic_packs#540]
**Describe the issue**
With FPS++'s "Static Mode" enabled, the game speed is affected; playing at 60 FPS makes the entire game run at double speed, for example. This applies to both gameplay, in-game menus, and the title screen.

**To Reproduce**
1. Open Cemu, and click "Options" > "Graphic packs" at the top-left
2. Enable/Select "The Legend of Zelda: Breath of the Wild" > "Mods" > "FPS++"
3. Set "Mode" to "Advanced Settings"
4. Set "Static Mode" to "Enabled (slowdown when under framerate limit)"
5. Launch The Legend of Zelda: Breath of the Wild

**Expected behavior**
The game runs at the specified frame rate (60 by default), while running at 100% game speed.

**Observed behavior**
The game runs at the specified frame rate, while running at a proportionately faster game speed.

**Desktop (please complete the following information):**
 - OS: Windows 10, 64-bit
 - GPU: NVIDIA GeForce RTX 2080 Ti, driver v496.13
 - Renderer: Vulkan
 - Version: Cemu v1.26.0d, Cemuhook v0.5.7.5, graphic packs v837, BotW v208 [EU]

**Comment by Crementif** [comment]
Will look into it today. We generally don't really test Static FPS, so thanks for reporting something that we missed.
