### ISSUE TITLE
[The Legend of Zelda: BOTW] Infinite Arrows Not Working

### ISSUE THREAD

**Issue by erikt311** [ActualMandM/cemu_graphic_packs#543]
**Describe the issue**
I can't seem to get this cheat to work. I have the latest version of CEMU, the graphics packs, and 1.5.0 for the game. 

Cemu shows it active (green) when running the game, but arrows are still empty. 

**Expected behavior**
Unsure. Are there any prereqs (does it require a new game or any specific or preexisting arrows in quiver or anything?). I expected to be able to shoot arrows unlimited. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - GPU: Nvidia 1060 6gb
 - Renderer Vulkan 
 - Version 1.26.0d

**Comment by Crementif** [comment]
Yeah, the mod requires you to have a single arrow to fire. It basically will never subtract any arrows from your total. I don't think this requirement is easily lifted, so probably won't be fixed to not have this requirement. In a way it's similar to Minecraft's infinite arrows, to make a weird comparison.

Will try to update the graphic pack description to clarify this in a future release, so thanks for reporting this. Could definitely see it causing some confusion.

**Comment by erikt311** [comment]
Got it. That was the missing piece. 

For what it's worth, I started with empty arrows. I first tried to enable the mod and couldn't get it to work, even when buying at least 1 arrow. 

I had to disable the mod, THEN buy one of each arrow, save, then enable the mod. 

Working now. 

Thanks!!
