### ISSUE TITLE
[BOTW] Why bsod gaming's preset got removed ?

### ISSUE THREAD

**Issue by Mewzax** [ActualMandM/cemu_graphic_packs#552]
bruh i re-downloaded cemu 10 minute ago and bsod preset was missing. i came here and boom saw https://github.com/ActualMandM/cemu_graphic_packs/commit/7f03b023319ec889167d93ec395cd09fc8a2cf2d

**Comment by ActualMandM** [comment]
As said on Discord:
> Personal reasons
> 
> I don't want to get into it as it would just be mainly bringing back up drama from over a year ago

**Comment by Mewzax** [comment]
Okie i ll setup by myself
