### ISSUE TITLE
[Hyrule Warriors] a way to change the aspect ratio

### ISSUE THREAD

**Issue by TinyGamer** [ActualMandM/cemu_graphic_packs#563]
I would like to be able to change the aspect ratio of the game independently from the resolution, this would be useful for people who want to play this game on the steam deck, seeing that currently you cant set the aspect ratio to 16:10.

**Comment by ActualMandM** [comment]
Can you try the 1280x800 resolution with the latest version of the graphic packs?

**Comment by TinyGamer** [comment]
tried it, works great
